### ISSUE TITLE
Possible bug in "@mixin column" in "_grid-system.scss".

### ISSUE THREAD

**Issue by RobertinoValue** [sehmaschine/mueller#6]
**EDITED:**
Replaced `last` with `large (full-width)`.
I meant last in the loop, not in a row of a webpage.

`@mixin column` :
https://github.com/sehmaschine/mueller/blob/master/sass/grid/_grid-system.scss#L93-L105

``` scss
// generates the columns
@mixin column($n, $max-unit, $col-width, $gutter-width, $first-column-class, $last-column-class) {
    @include column-base;
    @if $n == $max-unit {
        margin-left: 0 !important;
        margin-right: 0 !important;
        clear: both;
    } @else {
        margin-right: $gutter-width;
    }
    width: column-width($n, $col-width, $gutter-width);
    clear: none;
}
```

generates the following in `output.css` for a large (full-width) column :
(Only shown here for `g-d-24`, but also generated for `g-h-6`, `g-hl-6`, `g-tp-12`, `g-l-24`, `g-hr-24`)

``` css

/* line 136, ../../sass/grid/_grid-system.scss */
.g-d-24, .l-1c, .l-1c .c-1, .l-2c, .l-2cr, .l-3c, .l-4c, .l-test {
  float: left;
  *zoom: 1;
  margin-left: 0 !important;
  margin-right: 0 !important;
  clear: both;
  width: 940px;
  clear: none;
}
```

I think that the `clear: none;` should not be there for a large (full-width) column. But only for the shorter columns. So the scss code should be :

``` scss
// generates the columns
@mixin column($n, $max-unit, $col-width, $gutter-width, $first-column-class, $last-column-class) {
    @include column-base;
    @if $n == $max-unit {
        margin-left: 0 !important;
        margin-right: 0 !important;
        clear: both;
    } @else {
        margin-right: $gutter-width;
        clear: none;
    }
    width: column-width($n, $col-width, $gutter-width);
}
```
